### ISSUE TITLE
Persisting files fails if the path is not on the same device

### ISSUE THREAD

**Issue by zacps** [kardeiz/awmp#3]
On linux trying to persist a file can fail if the destination path is not on the same device.

`TempFilePersistError(PersistError { error: Os { code: 18, kind: Other, message: "Invalid cross-device link" }, file: NamedTempFile("/tmp/.tmpvSvDlP") })`

I'd like it if the underlying `NamedTempFile` was exposed, then I can do whatever I want with the file.

**Comment by kardeiz** [comment]
Hi @zacps,

I'm not sure if having access to the `NamedTempFile` would help very much, though I guess you could at least `read` the file.

I think the best way to handle this issue is to use the `Parts::configure` to specify the temp directory, like:

```rust
actix_web::App::new()
    .data(awmp::Parts::configure(|cfg| cfg.with_temp_dir("/mnt/somewhere")))
```

This will use `NamedTempFile::new_in`, and you shouldn't have trouble persisting your files (as long as the target is the same filesystem as `/mnt/somewhere`).

However, I'm not necessarily opposed to exposing the `NamedTempFile`.

**Comment by zacps** [comment]
In my case exposing a `NamedTempFile` works because I just need to read from the file and then it can be deleted. I don't want to have to write it to an intermediary location first, if possible.

For my use case the ideal API would expose a `Stream`  for each file like is done in the underlying actix-multipart API.

**Comment by kardeiz** [comment]
@zacps Okay, I've added `awmp::File::into_inner`, which returns the inner `NamedTempFile`, in [`0.4.1`](https://crates.io/crates/awmp/0.4.1).

I've also added a `text_fields` configuration option, which may be useful for your scenario. With this setting, you can define field names which should be treated as `texts` (using `Bytes`). If the files you want to read are small, you could use this to buffer them to `Bytes` objects. If your files are UTF8 strings, you can access them through `TextParts::as_pairs`, otherwise you will need to use the `Bytes` objects with `TextParts::into_inner`.

Closing this issue, but let me know if this does not work for you&mdash;
