### ISSUE TITLE
Actix-web 2.x support

### ISSUE THREAD

**Issue by 0x1793d1** [kardeiz/awmp#4]
Hello!

Do you have plans to support actix-web 2.x?
It would be really great!

Thanks

**Comment by kardeiz** [comment]
@0x1793d1 Yes! 

I'm thinking I'll support both 1.x and 2.x using feature flags and renamed dependencies, with 2.x being the default. I'll be working on this tomorrow, and will post here when it is ready&mdash;

**Comment by 0x1793d1** [comment]
Cool!
I can't wait to try the update.

**Comment by kardeiz** [comment]
@0x1793d1 Hi, I've released [`0.5.0`](https://crates.io/crates/awmp/0.5.0), which has support for actix-web 2.x by default. Configuration for usage with 1.x is described in the [README](https://github.com/kardeiz/awmp/blob/master/README.md).

I'm going to close this now, but please let me know if you have any issues with the new version.

**Comment by 0x1793d1** [comment]
It works well for me.
Thanks!

**Comment by kardeiz** [comment]
Hey @0x1793d1, if you are using `awmp::PartsConfig` to set limits, please upgrade to [`0.5.1`](https://crates.io/crates/awmp/0.5.1), which I just pushed out.

`actix-web` 2.0 changed how `HttpRequest::app_data` works: you now have to explicitly ask for `Data<T>` in `HttpRequest::app_data` if you use `App::data` to insert data (instead of asking for just `T`). This meant that any `PartsConfig` added was being ignored in `0.5.0`. I also created a PR on `actix-web` to call out this behavior: https://github.com/actix/actix-web/pull/1265.

**Comment by 0x1793d1** [comment]
Hi @kardeiz, indeed, thanks!
