### ISSUE TITLE
[feature request] parts.texts.as_hashmap()

### ISSUE THREAD

**Issue by shinglyu** [kardeiz/awmp#6]
Currently, I use the following code to get a hashmap of text fields:

```
let text_fields: HashMap<_, _> = parts.texts.as_pairs().into_iter().collect();
text_fields.get("my_key");
```

If you think it's useful to add an `as_hashmap()` function on `TextParts`, I can try to create a PR.

**Comment by kardeiz** [comment]
Hi @shinglyu, sure, I think this would help with a pretty common use case!

The reason I didn't add this initially is because 1) it is pretty easy to to collect the fields into a hashmap as in your example and 2) if there are multiple values for a given key, this will drop the first value.

If you do create a PR, please name the method `as_hash_map` (note the second underscore), to match the standard library convention, and add a doc comment noting that it is only for single-valued pairs.

**Comment by littledivy** [comment]
@kardeiz I do think `HashMaps` would make it much for easy.
