### ISSUE TITLE
[feature request] persist the file to a randomized name

### ISSUE THREAD

**Issue by shinglyu** [kardeiz/awmp#7]
`File::persist()` saved the file using the sanitized filename. But for security reason, I'd love to save the file using a random name. This way an attacker won't be able to predict the path to the file. This can be implemented in different ways:

1. add an `persist_randomize()` function to persist the file using a randomized name.
2. allow the user to pass an optional filename parameter to `persist()`, so they can generate a random filename outside.
3. allow the user to pass a closure to `persist()` to transform the filename before saving. 

I'd love to help writing a PR if we can reach an agreement on which path to take.

**Comment by kardeiz** [comment]
@shinglyu Yes, I think this is a good idea.

I think my preferred way to do this would be to provide a `persist_at` method, which would take a full path (including filename). Users would be responsible for generating the randomized filename. I would deprecate the existing `persist` and rename it to `persist_in` (to indicate that the path provided should be a directory).

Alternately, we could provide a `File::use_persisted_file_name` which would be used like:

```rust
parts
    .files
    .take("file")
    .pop()
    .unwrap()
    .use_persisted_file_name(uuid::Uuid::new_v4().to_string())
    .persist(my_files_folder)
    .unwrap();
```

I think this would be preferable if you or others use the `File::persist_with_permissions` method. But I think `File::persist_with_permissions` is probably not very useful; I only added it because I had a weird filesystem setup where I needed to change the permissions of the tempfile before persisting it.

What do you think?

Thanks for the issue!

Jacob

**Comment by iwismer** [comment]
A `.persist_at()` method would be super helpful for me, as I would like to ignore the received file name and simply use a generated file name.

**Comment by kardeiz** [comment]
@iwismer I've added this in [`0.5.4`](https://docs.rs/awmp/0.5.4/awmp/). I'm going to go ahead and close this, but let me know if you have any issues using it.
